// TODO - CHANGE initialCountry
export const initialCountry = {
  name: {
    en: 'Ukraine',
    da: 'Ukraine',
    ru: 'Украина',
    pl: 'Ukraina',
    ua: 'Україна',
    cz: 'Ukrajina',
    by: 'Украіна',
    pt: 'Ucrânia',
    es: 'Ucrania',
    ro: 'Ucraina',
    bg: 'Украйна',
    de: 'Ukraine',
    fr: 'Ukraine',
    nl: 'Oekraïne',
    it: 'Ucraina',
    cn: '乌克兰',
    zh: '烏克蘭',
    ee: 'Ukraina',
    jp: 'ウクライナ',
    he: 'אוקראינה',
    el: 'Ουκρανία',
    ar: 'أوكرانيا',
    tr: 'Ukrayna',
  },
  dial_code: '+380',
  code: 'UA',
  flag: '🇺🇦',
}
