
auth.token=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

defaults.org=artrvnk
defaults.project=volito-test-app

defaults.url=https://sentry.io/
